name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/secure-crud:latest .

      # Step 4: Tag image with commit SHA
      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/secure-crud:latest \
          ${{ secrets.DOCKER_USERNAME }}/secure-crud:${{ github.sha }}

      # Step 5: Push images to Docker Hub
      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/secure-crud:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/secure-crud:${{ github.sha }}
